@Echo Off
SetLocal
Title "Waiting for the GUI to close"

Set HeaderName=comms.h
Set OutputName=%HeaderName:.h=.py%

Echo # Do not edit - Auto-generated by %~nx0 > %OutputName%
Echo. >> %OutputName%
Call sed -e "s/const [^ ]* /CONST_/" -e "s/;/	# ;/" %HeaderName% >> %OutputName%

Call python AsyncIOdemoGUI.py
If ErrorLevel 1 Pause
