@Echo Off
Title AsyncIOdemo GUI
SetLocal

Set HeaderName=comms.h
Set OutputName=PythonGUI\%HeaderName:.h=.py%

Echo # Do not edit - Auto-generated by %~nx0 > %OutputName%
Echo. >> %OutputName%
sed -e "s/const [^ ]* /CONST_/" -e "s/;/	# ;/" %HeaderName% >> %OutputName%

Title Waiting for the GUI to close
python PythonGUI\AsyncIOdemoGUI.py

EndLocal
