# Do not edit - Auto-generated by AsyncIOdemoGUI.cmd 
 
#ifndef COMMS_H                 // This is a header file for the Arduino sketch
#define COMMS_H

CONST_commsBaudRate = 115200	# ;
CONST_commsTimeout = 1	# ;

CONST_msgStartMarker = '<'	# ;
CONST_msgEndMarker = '>'	# ;

CONST_msgSetServoAngle = "SetServoAngle: "	# ;
CONST_msgSetRedLEDValue = "SetRedLEDValue: "	# ;
CONST_msgSetGreenLEDValue = "SetGreenLEDValue: "	# ;
CONST_msgSetBlueLEDValue = "SetBlueLEDValue: "	# ;
CONST_msgTurnOffRGBLEDs = "TurnOffRGBLEDs"	# ;
CONST_msgLEDon = "SwitchLEDon"	# ;
CONST_msgLEDoff = "SwitchLEDoff"	# ;
CONST_msgButtonPressedCount = "ButtonPressedCount: "	# ;
CONST_msgPotentiometerReading = "PotentiometerReading: "	# ;

#endif
